version: '3.5'

services:

  #build:
  #  privileged: true

  nvme:
    privileged: true
    build:
        context: .
        dockerfile: Dockerfile
        # build host dir with docker dir
    volumes:
        - './image:/outport'
